version: "3.8"

services:
  nginx:
    build: .
    container_name: waf-nginx
    ports:
      - "8080:80"


# version: "3.8"

# services:
#   nginx:
#     build: .
#     image: owasp/modsecurity:nginx-alpine
#     container_name: waf-nginx
#     ports:
#       - "8080:80"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./nginx/modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
#       - ./nginx/modsecurity/crs-setup.conf:/etc/modsecurity.d/crs-setup.conf:ro
#       - ./nginx/modsecurity/rules:/etc/modsecurity.d/rules:ro
#       - ./nginx/html:/usr/share/nginx/html:ro         # static test html file