#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/k8s/02-configmaps-only.yaml"

indent_file() {
  awk '{ sub(/[[:space:]]+$/, ""); if ($0 == "") print ""; else print "    " $0 }' "$ROOT_DIR/$1"
}

indent_fluent_bit_conf() {
  sed 's/Brokers     kafka:9092/Brokers     kafka.waf-processing.svc.cluster.local:9092/' "$ROOT_DIR/fluent-bit/fluent-bit.conf" \
    | awk '{ sub(/[[:space:]]+$/, ""); if ($0 == "") print ""; else print "    " $0 }'
}

indent_ksqldb_init() {
  sed 's|^KSQLDB_URL=.*|KSQLDB_URL="${KSQLDB_URL:-http://ksqldb.waf-processing.svc.cluster.local:8088}"|' "$ROOT_DIR/ksqldb/init-ksqldb.sh" \
    | awk '{ sub(/[[:space:]]+$/, ""); if ($0 == "") print ""; else print "    " $0 }'
}

emit_kafka_topics_script() {
  cat <<'SCRIPT'
    #!/bin/bash
    set -euo pipefail

    BROKER="${BROKER:-kafka.waf-processing.svc.cluster.local:9092}"

    echo "Waiting for Kafka to be ready..."
    until kafka-topics --bootstrap-server "$BROKER" --list >/dev/null 2>&1; do
      echo "Kafka not ready yet..."
      sleep 2
    done

    create() {
      local topic="$1"
      local partitions="$2"
      local rf="$3"
      shift 3 || true
      kafka-topics --bootstrap-server "$BROKER" --create --if-not-exists \
        --topic "$topic" --partitions "$partitions" --replication-factor "$rf" "$@"
      kafka-topics --bootstrap-server "$BROKER" --describe --topic "$topic" >/dev/null 2>&1 || true
      echo "Ensured topic $topic"
    }

    echo "Creating topics from kafka/ensure-topics.sh contract..."
SCRIPT
  awk '
    /^create_topic "/ {
      line=$0
      sub(/[[:space:]]+#.*/, "", line)
      gsub(/"/, "", line)
      split(line, parts, /[[:space:]]+/)
      topic=parts[2]
      partitions=parts[3]
      rf=parts[4]
      config=""
      for (i=5; i<=length(parts); i++) {
        if (parts[i] != "") {
          config = config " --config " parts[i]
        }
      }
      printf "    create \"%s\" %s %s%s\n", topic, partitions, rf, config
    }
  ' "$ROOT_DIR/kafka/ensure-topics.sh"
  cat <<'SCRIPT'

    echo "Topics created:"
    kafka-topics --bootstrap-server "$BROKER" --list
SCRIPT
}

emit_influxdb_config() {
  local namespace="$1"
  cat <<YAML
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: ${namespace}
data:
  influxdb-org: "\${INFLUXDB_ORG}"
  influxdb-bucket: "\${INFLUXDB_BUCKET}"

YAML
}

emit_influxdb_secret() {
  local namespace="$1"
  cat <<YAML
---
apiVersion: v1
kind: Secret
metadata:
  name: waf-influxdb-secrets
  namespace: ${namespace}
type: Opaque
stringData:
  influxdb-token: "\${INFLUXDB_TOKEN}"
  influxdb-admin-password: "\${INFLUXDB_ADMIN_PASSWORD}"

YAML
}

emit_auth_secret() {
  cat <<'YAML'
---
apiVersion: v1
kind: Secret
metadata:
  name: waf-auth-secrets
  namespace: waf-system
type: Opaque
stringData:
  google-client-id: "${GOOGLE_CLIENT_ID}"
  google-client-secret: "${GOOGLE_CLIENT_SECRET}"
  jwt-secret: "${JWT_SECRET}"
  nextauth-secret: "${NEXTAUTH_SECRET}"

YAML
}

emit_clickhouse_secret() {
  local namespace="$1"
  cat <<YAML
---
apiVersion: v1
kind: Secret
metadata:
  name: waf-clickhouse-secrets
  namespace: ${namespace}
type: Opaque
stringData:
  clickhouse-password: "\${CLICKHOUSE_PASSWORD}"

YAML
}

indent_logstash_template() {
  local template_file="$ROOT_DIR/logstash/pipeline/waf-logs-template.json"
  if [ -f "$template_file" ]; then
    awk '{ sub(/[[:space:]]+$/, ""); if ($0 == "") print ""; else print "    " $0 }' "$template_file"
  else
    cat <<'JSON'
    {
      "index_patterns": ["waf-logs-*"],
      "template": {
        "mappings": {
          "properties": {
            "timestamp": { "type": "date" },
            "client_ip": { "type": "ip" },
            "method": { "type": "keyword" },
            "uri": {
              "type": "text",
              "fields": {
                "keyword": { "type": "keyword", "ignore_above": 2048 }
              }
            },
            "status_code": { "type": "integer" },
            "rule_id": { "type": "keyword" },
            "severity": { "type": "keyword" },
            "attack_type": { "type": "keyword" },
            "message": { "type": "text" },
            "blocked": { "type": "boolean" },
            "country": { "type": "keyword" },
            "user_agent": { "type": "text" },
            "response_time": { "type": "long" },
            "tx_id": { "type": "keyword" },
            "classification_track": { "type": "keyword" }
          }
        }
      }
    }
JSON
  fi
}

{
  cat <<'YAML'
# Generated by scripts/generate-k8s-configmaps.sh.
# Do not edit embedded file contents by hand; update the canonical source files.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: waf-system
data:
  fluent-bit.conf: |
YAML
  indent_fluent_bit_conf
  cat <<'YAML'
  parsers.conf: |
YAML
  indent_file "fluent-bit/parsers.conf"
  cat <<'YAML'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: waf-classifier-config
  namespace: waf-system
data:
  waf_classifier.lua: |
YAML
  indent_file "fluent-bit/waf_classifier.lua"
  echo

  emit_influxdb_config "waf-data"
  emit_influxdb_config "waf-system"
  emit_influxdb_config "waf-processing"
  emit_influxdb_secret "waf-data"
  emit_influxdb_secret "waf-system"
  emit_influxdb_secret "waf-processing"
  emit_clickhouse_secret "waf-data"
  emit_clickhouse_secret "waf-processing"
  emit_auth_secret

  cat <<'YAML'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: waf-config
  namespace: waf-system
data:
  public-domain: "${DOMAIN:-http://localhost:3001}"
  cookie-domain: "${COOKIE_DOMAIN:-localhost}"
  cookie-secure: "${COOKIE_SECURE:-false}"
  google-oauth-redirect-uri: "${GOOGLE_OAUTH_REDIRECT_URI:-http://localhost:3001/login/oauth2/code/google}"
  oauth-callback-base-url: "${OAUTH_CALLBACK_BASE_URL:-http://localhost:3001}"
  oauth-default-redirect-url: "${OAUTH_DEFAULT_REDIRECT_URL:-http://localhost:3001}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-script
  namespace: waf-processing
data:
  ensure-topics.sh: |
YAML
  emit_kafka_topics_script
  cat <<'YAML'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ksqldb-ddl
  namespace: waf-processing
data:
  ddl.sql: |
YAML
  indent_file "ksqldb/ddl.sql"
  cat <<'YAML'
  init-ksqldb.sh: |
YAML
  indent_ksqldb_init
  cat <<'YAML'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: waf-system
data:
  pipeline.conf: |
YAML
  indent_file "logstash/pipeline/pipeline.conf"
  cat <<'YAML'
  waf-logs-template.json: |
YAML
  indent_logstash_template
  cat <<'YAML'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-initdb
  namespace: waf-data
data:
  init.sql: |
YAML
  indent_file "clickhouse/init.sql"
} > "$OUT_FILE"

echo "Generated $OUT_FILE"
